{
  "formatVersion": "1.1",
  "component": {
    "group": "com.app",
    "module": "library-ads",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.5.0"
          }
        },
        {
          "group": "com.pubscale.ads",
          "module": "admob-adapter",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.19.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.1.3"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "5.0.9"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "library-ads-0.0.1.aar",
          "url": "library-ads-0.0.1.aar",
          "size": 626804,
          "sha512": "51f9540863fa9f651c80cb0dee72caca0f01f6c4960b7ff0183fb96a74b4f4aaf8ebd12c2f0ff0ec37ce9eaad4c540551d7eccd121b8fcc427ca0a91fb7ec2bd",
          "sha256": "82ff31554028e52ba66c5d992fcced67f124f2fb6b0e52790e9475eff45e6459",
          "sha1": "8a5f31511ace5cd6d33061fc13ab04d83a85226f",
          "md5": "5b0329babe8e7d0e421ecc2a9cab211d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.5.0"
          }
        },
        {
          "group": "com.pubscale.ads",
          "module": "admob-adapter",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.19.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.1.3"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "5.0.9"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "library-ads-0.0.1.aar",
          "url": "library-ads-0.0.1.aar",
          "size": 626804,
          "sha512": "51f9540863fa9f651c80cb0dee72caca0f01f6c4960b7ff0183fb96a74b4f4aaf8ebd12c2f0ff0ec37ce9eaad4c540551d7eccd121b8fcc427ca0a91fb7ec2bd",
          "sha256": "82ff31554028e52ba66c5d992fcced67f124f2fb6b0e52790e9475eff45e6459",
          "sha1": "8a5f31511ace5cd6d33061fc13ab04d83a85226f",
          "md5": "5b0329babe8e7d0e421ecc2a9cab211d"
        }
      ]
    }
  ]
}
