{
  "formatVersion": "1.1",
  "component": {
    "group": "com.app",
    "module": "library-ads",
    "version": "0.0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.libraries.ads.mobile.sdk",
          "module": "ads-mobile-sdk",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.pubscale.ads",
          "module": "admob-adapter",
          "version": {
            "requires": "1.0.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.19.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.1.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "5.0.9"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "library-ads-0.0.2.1.aar",
          "url": "library-ads-0.0.2.1.aar",
          "size": 635678,
          "sha512": "af95edc375fadab729c1990b849cfd23a9df43050a6f37317c60f8b6467df5f7663f8db56ddc792503a0ffbe222941b4933974b164f01d4ab30a6a70521b1c73",
          "sha256": "5ec407c3c52fa040fdc821b41527c6858899eec1715ee3154f10dcf23d4177a0",
          "sha1": "6144fe2c2f3a298cc5e51ff8a042d4a3576d8bab",
          "md5": "77ae53be8cc89ff5ff2b5a680a9dcfde"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.19.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.android.libraries.ads.mobile.sdk",
          "module": "ads-mobile-sdk",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.pubscale.ads",
          "module": "admob-adapter",
          "version": {
            "requires": "1.0.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.19.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.1.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "5.0.9"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "9.3.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-base"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "library-ads-0.0.2.1.aar",
          "url": "library-ads-0.0.2.1.aar",
          "size": 635678,
          "sha512": "af95edc375fadab729c1990b849cfd23a9df43050a6f37317c60f8b6467df5f7663f8db56ddc792503a0ffbe222941b4933974b164f01d4ab30a6a70521b1c73",
          "sha256": "5ec407c3c52fa040fdc821b41527c6858899eec1715ee3154f10dcf23d4177a0",
          "sha1": "6144fe2c2f3a298cc5e51ff8a042d4a3576d8bab",
          "md5": "77ae53be8cc89ff5ff2b5a680a9dcfde"
        }
      ]
    }
  ]
}
